FROM ubuntu:24.04@sha256:d1e2e92c075e5ca139d51a140fff46f84315c0fdce203eab2807c7e495eff4f9
RUN apt-get update && apt-get install -y curl git wget unzip xz-utils libglu1-mesa ca-certificates
RUN git clone https://github.com/flutter/flutter.git /opt/flutter --branch stable --depth 1
ENV PATH="/opt/flutter/bin:${PATH}"
RUN flutter --version
RUN flutter doctor -v
