FROM ubuntu:24.04
RUN apt-get update && apt-get install -y curl git wget unzip xz-utils libglu1-mesa ca-certificates
RUN git clone https://github.com/flutter/flutter.git /opt/flutter --branch stable --depth 1
ENV PATH="/opt/flutter/bin:${PATH}"
RUN flutter --version
RUN flutter doctor -v
