FROM ubuntu:24.04@sha256:186072bba1b2f436cbb91ef2567abca677337cfc786c86e107d25b7072feef0c
RUN apt-get update && apt-get install -y curl git wget unzip xz-utils libglu1-mesa ca-certificates
RUN git clone https://github.com/flutter/flutter.git /opt/flutter --branch stable --depth 1
ENV PATH="/opt/flutter/bin:${PATH}"
RUN flutter --version
RUN flutter doctor -v
