import 'buzztap_models.dart';
import '../../../../core/i18n/app_localizations.dart';

List<BuzzTapCard> generateBuzzTapExpansion(AppLocalizations l10n) {
  return [
    BuzzTapCard(
      id: 'w100',
      emoji: '👋',
      text: l10n.get('bt_card_w100'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w101',
      emoji: '🎲',
      text: l10n.get('bt_card_w101'),
      sips: 1,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w102',
      emoji: '👕',
      text: l10n.get('bt_card_w102'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w103',
      emoji: '🤔',
      text: l10n.get('bt_card_w103'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w104',
      emoji: '🍻',
      text: l10n.get('bt_card_w104'),
      sips: 1,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w105',
      emoji: '📱',
      text: l10n.get('bt_card_w105'),
      sips: 1,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w106',
      emoji: '🎶',
      text: l10n.get('bt_card_w106'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w107',
      emoji: '🗓️',
      text: l10n.get('bt_card_w107'),
      sips: 3,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w108',
      emoji: '🕰️',
      text: l10n.get('bt_card_w108'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w109',
      emoji: '👟',
      text: l10n.get('bt_card_w109'),
      sips: 3,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w110',
      emoji: '🎒',
      text: l10n.get('bt_card_w110'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w111',
      emoji: '👓',
      text: l10n.get('bt_card_w111'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w112',
      emoji: '😴',
      text: l10n.get('bt_card_w112'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w113',
      emoji: '🧊',
      text: l10n.get('bt_card_w113'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w114',
      emoji: '🔥',
      text: l10n.get('bt_card_w114'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w115',
      emoji: '🖐️',
      text: l10n.get('bt_card_w115'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w116',
      emoji: '🗣️',
      text: l10n.get('bt_card_w116'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w117',
      emoji: '🌍',
      text: l10n.get('bt_card_w117'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w118',
      emoji: '🦮',
      text: l10n.get('bt_card_w118'),
      sips: 1,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w119',
      emoji: '📺',
      text: l10n.get('bt_card_w119'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w120',
      emoji: '💤',
      text: l10n.get('bt_card_w120'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w121',
      emoji: '🏃',
      text: l10n.get('bt_card_w121'),
      sips: 3,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w122',
      emoji: '🍎',
      text: l10n.get('bt_card_w122'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'w123',
      emoji: '🪙',
      text: l10n.get('bt_card_w123'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'w124',
      emoji: '🥤',
      text: l10n.get('bt_card_w124'),
      sips: 2,
      category: BuzzTapCategory.warmup,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p100',
      emoji: '🎉',
      text: l10n.get('bt_card_p100'),
      sips: 1,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p101',
      emoji: '💃',
      text: l10n.get('bt_card_p101'),
      sips: 4,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p102',
      emoji: '🪩',
      text: l10n.get('bt_card_p102'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 4,
    ),
    BuzzTapCard(
      id: 'p103',
      emoji: '👑',
      text: l10n.get('bt_card_p103'),
      sips: 4,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p104',
      emoji: '🎈',
      text: l10n.get('bt_card_p104'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p105',
      emoji: '📸',
      text: l10n.get('bt_card_p105'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p106',
      emoji: '🎤',
      text: l10n.get('bt_card_p106'),
      sips: 4,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p107',
      emoji: '🔥',
      text: l10n.get('bt_card_p107'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p108',
      emoji: '🎸',
      text: l10n.get('bt_card_p108'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p109',
      emoji: '🎭',
      text: l10n.get('bt_card_p109'),
      sips: 4,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p110',
      emoji: '🤝',
      text: l10n.get('bt_card_p110'),
      sips: 0,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p111',
      emoji: '🍺',
      text: l10n.get('bt_card_p111'),
      sips: 5,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p112',
      emoji: '🦁',
      text: l10n.get('bt_card_p112'),
      sips: 2,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p113',
      emoji: '🤫',
      text: l10n.get('bt_card_p113'),
      sips: 2,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p114',
      emoji: '🤸',
      text: l10n.get('bt_card_p114'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p115',
      emoji: '🎩',
      text: l10n.get('bt_card_p115'),
      sips: 4,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p116',
      emoji: '🥳',
      text: l10n.get('bt_card_p116'),
      sips: 1,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p117',
      emoji: '🍕',
      text: l10n.get('bt_card_p117'),
      sips: 2,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p118',
      emoji: '🥤',
      text: l10n.get('bt_card_p118'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p119',
      emoji: '⏱️',
      text: l10n.get('bt_card_p119'),
      sips: 0,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p120',
      emoji: '🤹',
      text: l10n.get('bt_card_p120'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p121',
      emoji: '🚑',
      text: l10n.get('bt_card_p121'),
      sips: 2,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p122',
      emoji: '🦸',
      text: l10n.get('bt_card_p122'),
      sips: 0,
      category: BuzzTapCategory.party,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'p123',
      emoji: '🗣️',
      text: l10n.get('bt_card_p123'),
      sips: 0,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'p124',
      emoji: '🤣',
      text: l10n.get('bt_card_p124'),
      sips: 3,
      category: BuzzTapCategory.party,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h100',
      emoji: '💋',
      text: l10n.get('bt_card_h100'),
      sips: 4,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h101',
      emoji: '😈',
      text: l10n.get('bt_card_h101'),
      sips: 5,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h102',
      emoji: '👀',
      text: l10n.get('bt_card_h102'),
      sips: 3,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h103',
      emoji: '🔥',
      text: l10n.get('bt_card_h103'),
      sips: 4,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h104',
      emoji: '🍑',
      text: l10n.get('bt_card_h104'),
      sips: 0,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h105',
      emoji: '🥵',
      text: l10n.get('bt_card_h105'),
      sips: 3,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h106',
      emoji: '🤫',
      text: l10n.get('bt_card_h106'),
      sips: 4,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h107',
      emoji: '🍓',
      text: l10n.get('bt_card_h107'),
      sips: 3,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h108',
      emoji: '🌹',
      text: l10n.get('bt_card_h108'),
      sips: 6,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h109',
      emoji: '🖤',
      text: l10n.get('bt_card_h109'),
      sips: 5,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h110',
      emoji: '💃',
      text: l10n.get('bt_card_h110'),
      sips: 4,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h111',
      emoji: '💦',
      text: l10n.get('bt_card_h111'),
      sips: 3,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h112',
      emoji: '👅',
      text: l10n.get('bt_card_h112'),
      sips: 0,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h113',
      emoji: '💘',
      text: l10n.get('bt_card_h113'),
      sips: 0,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h114',
      emoji: '🚿',
      text: l10n.get('bt_card_h114'),
      sips: 2,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h115',
      emoji: '🧴',
      text: l10n.get('bt_card_h115'),
      sips: 3,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h116',
      emoji: '👄',
      text: l10n.get('bt_card_h116'),
      sips: 3,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h117',
      emoji: '😻',
      text: l10n.get('bt_card_h117'),
      sips: 5,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h118',
      emoji: '🌶️',
      text: l10n.get('bt_card_h118'),
      sips: 0,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h119',
      emoji: '📸',
      text: l10n.get('bt_card_h119'),
      sips: 4,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h120',
      emoji: '🍒',
      text: l10n.get('bt_card_h120'),
      sips: 3,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h121',
      emoji: '🍷',
      text: l10n.get('bt_card_h121'),
      sips: 3,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h122',
      emoji: '🙈',
      text: l10n.get('bt_card_h122'),
      sips: 5,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'h123',
      emoji: '💄',
      text: l10n.get('bt_card_h123'),
      sips: 2,
      category: BuzzTapCategory.hot,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'h124',
      emoji: '✨',
      text: l10n.get('bt_card_h124'),
      sips: 1,
      category: BuzzTapCategory.hot,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e100',
      emoji: '💀',
      text: l10n.get('bt_card_e100'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e101',
      emoji: '🌪️',
      text: l10n.get('bt_card_e101'),
      sips: 4,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e102',
      emoji: '🧨',
      text: l10n.get('bt_card_e102'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e103',
      emoji: '🪒',
      text: l10n.get('bt_card_e103'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e104',
      emoji: '📞',
      text: l10n.get('bt_card_e104'),
      sips: 8,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e105',
      emoji: '🤢',
      text: l10n.get('bt_card_e105'),
      sips: 6,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e106',
      emoji: '💥',
      text: l10n.get('bt_card_e106'),
      sips: 5,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e107',
      emoji: '🤡',
      text: l10n.get('bt_card_e107'),
      sips: 8,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e108',
      emoji: '🧦',
      text: l10n.get('bt_card_e108'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e109',
      emoji: '🗑️',
      text: l10n.get('bt_card_e109'),
      sips: 10,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e110',
      emoji: '🧊',
      text: l10n.get('bt_card_e110'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e111',
      emoji: '🥚',
      text: l10n.get('bt_card_e111'),
      sips: 8,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e112',
      emoji: '👅',
      text: l10n.get('bt_card_e112'),
      sips: 10,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e113',
      emoji: '💸',
      text: l10n.get('bt_card_e113'),
      sips: 5,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e114',
      emoji: '😭',
      text: l10n.get('bt_card_e114'),
      sips: 6,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e115',
      emoji: '📱',
      text: l10n.get('bt_card_e115'),
      sips: 3,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e116',
      emoji: '🔥',
      text: l10n.get('bt_card_e116'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e117',
      emoji: '🤝',
      text: l10n.get('bt_card_e117'),
      sips: 5,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e118',
      emoji: '🥊',
      text: l10n.get('bt_card_e118'),
      sips: 5,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e119',
      emoji: '👗',
      text: l10n.get('bt_card_e119'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e120',
      emoji: '🏃',
      text: l10n.get('bt_card_e120'),
      sips: 7,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e121',
      emoji: '🛀',
      text: l10n.get('bt_card_e121'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e122',
      emoji: '👟',
      text: l10n.get('bt_card_e122'),
      sips: 10,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
    BuzzTapCard(
      id: 'e123',
      emoji: '🗣️',
      text: l10n.get('bt_card_e123'),
      sips: 5,
      category: BuzzTapCategory.extreme,
      minPlayers: 3,
    ),
    BuzzTapCard(
      id: 'e124',
      emoji: '☠️',
      text: l10n.get('bt_card_e124'),
      sips: 0,
      category: BuzzTapCategory.extreme,
      minPlayers: 2,
    ),
  ];
}
