import '../models/factquest_models.dart';

// Helper to create cards compactly
FactQuestCard _rf(String id, String emoji, String url) => FactQuestCard(
  id: id,
  text: 'fq_card_${id}_text',
  explanation: 'fq_card_${id}_expl',
  sourceUrl: url,
  emoji: emoji,
  category: FactQuestCategory.randomFacts,
);
FactQuestCard _dw(String id, String emoji, String url) => FactQuestCard(
  id: id,
  text: 'fq_card_${id}_text',
  explanation: 'fq_card_${id}_expl',
  sourceUrl: url,
  emoji: emoji,
  category: FactQuestCategory.dumbWaysToDie,
);

final List<FactQuestCard> factQuestDatabase = [
  // ── Random Facts (200+) ───────────────────────────────────────────────────
  _rf(
    'rf001',
    '🍯',
    'https://www.nationalgeographic.com/animals/article/honey-never-spoils',
  ),
  _rf(
    'rf002',
    '🤭',
    'https://www.guinnessworldrecords.com/world-records/longest-hiccupping-spree',
  ),
  _rf('rf003', '🌊', 'https://oceanservice.noaa.gov/facts/ocean.html'),
  _rf(
    'rf004',
    '🌲',
    'https://www.smithsonianmag.com/smart-news/there-are-more-trees-earth-stars-known-universe-180956612/',
  ),
  _rf('rf005', '🏯', 'https://www.britannica.com/place/Great-Wall-of-China'),
  _rf(
    'rf006',
    '🐙',
    'https://www.mentalfloss.com/article/57800/15-things-you-might-not-know-about-octopuses',
  ),
  _rf('rf007', '🪐', 'https://www.nasa.gov/solar-system/planets/venus/'),
  _rf('rf008', '🦐', 'https://www.worldwildlife.org/species/mantis-shrimp'),
  _rf(
    'rf009',
    '⚡',
    'https://www.bbc.com/future/article/20150126-the-silent-killer-you-cant-smell',
  ),
  _rf(
    'rf010',
    '🔬',
    'https://www.nationalgeographic.com/animals/article/tardigrades',
  ),
  _rf(
    'rf011',
    '🍌',
    'https://www.livescience.com/44629-bananas-are-radioactive.html',
  ),
  _rf(
    'rf012',
    '🏛️',
    'https://www.history.com/news/cleopatra-ancient-egypt-facts',
  ),
  _rf(
    'rf013',
    '🌏',
    'https://www.scientificamerican.com/article/how-much-of-the-ocean-have-we-explored/',
  ),
  _rf('rf014', '💀', 'https://www.britannica.com/science/human-body'),
  _rf(
    'rf015',
    '🐬',
    'https://www.nationalgeographic.com/animals/article/dolphins-facts',
  ),
  _rf('rf016', '🐳', 'https://www.britannica.com/animal/blue-whale'),
  _rf(
    'rf017',
    '📏',
    'https://www.guinnessworldrecords.com/world-records/tallest-man-ever',
  ),
  _rf('rf018', '☀️', 'https://www.nasa.gov/image-article/suns-corona/'),
  _rf('rf019', '🦩', 'https://www.britannica.com/animal/flamingo'),
  _rf('rf020', '🌍', 'https://www.space.com/17638-how-big-is-earth.html'),
  _rf('rf021', '🪰', 'https://www.britannica.com/animal/housefly'),
  _rf('rf022', '🏟️', 'https://www.history.com/topics/ancient-rome/colosseum'),
  _rf(
    'rf023',
    '⭐',
    'https://www.scientificamerican.com/article/how-many-stars-are-in-the-universe/',
  ),
  _rf(
    'rf024',
    '🐦‍⬛',
    'https://www.nationalgeographic.com/animals/article/how-do-crows-use-tools',
  ),
  _rf('rf025', '🧬', 'https://www.britannica.com/science/DNA'),
  _rf(
    'rf026',
    '🌳',
    'https://education.nationalgeographic.org/resource/amazonfact/',
  ),
  _rf('rf027', '🦒', 'https://www.britannica.com/animal/giraffe'),
  _rf('rf028', '🔋', 'https://www.bbc.com/news/science-environment-26267918'),
  _rf('rf029', '🏔️', 'https://www.britannica.com/place/Lake-Baikal'),
  _rf(
    'rf030',
    '🐍',
    'https://www.nationalgeographic.com/animals/article/electric-eel',
  ),
  _rf('rf031', '💡', 'https://www.britannica.com/science/speed-of-light'),
  _rf('rf032', '🦆', 'https://www.worldwildlife.org/species/platypus'),
  _rf('rf033', '🪐', 'https://www.nasa.gov/solar-system/planets/saturn/'),
  _rf('rf034', '❤️', 'https://www.britannica.com/science/human-heart'),
  _rf(
    'rf035',
    '🚀',
    'https://www.space.com/18090-alpha-centauri-nearest-star-system.html',
  ),
  _rf(
    'rf036',
    '🐜',
    'https://www.nationalgeographic.com/animals/article/ant-facts',
  ),
  _rf('rf037', '🏜️', 'https://www.britannica.com/place/Sahara-desert-Africa'),
  _rf(
    'rf038',
    '🦠',
    'https://www.livescience.com/37115-how-many-cells-in-body.html',
  ),
  _rf('rf039', '⚡', 'https://www.britannica.com/biography/Nikola-Tesla'),
  _rf(
    'rf040',
    '🦈',
    'https://www.nationalgeographic.com/science/article/greenland-sharks-oldest-vertebrates',
  ),
  _rf('rf041', '🗺️', 'https://www.britannica.com/place/Russia'),
  _rf('rf042', '📐', 'https://www.history.com/topics/ancient-americas/maya'),
  _rf(
    'rf043',
    '🪟',
    'https://www.scientificamerican.com/article/fact-or-fiction-glass-is-a-liquid/',
  ),
  _rf('rf044', '🧊', 'https://www.bbc.com/news/science-environment-22031074'),
  _rf(
    'rf045',
    '🐱',
    'https://www.nationalgeographic.com/animals/article/how-do-cats-purr',
  ),
  _rf('rf046', '🌐', 'https://www.britannica.com/technology/Internet'),
  _rf('rf047', '🐀', 'https://www.history.com/topics/middle-ages/black-death'),
  _rf('rf048', '🦞', 'https://www.britannica.com/animal/pistol-shrimp'),
  _rf('rf049', '🧠', 'https://www.britannica.com/science/brain'),
  _rf(
    'rf050',
    '🐘',
    'https://www.nationalgeographic.com/animals/article/elephant-facts',
  ),
  _rf('rf051', '🌋', 'https://www.britannica.com/place/Mount-Everest'),
  _rf('rf052', '🦴', 'https://www.livescience.com/52136-tongue-print.html'),
  _rf('rf053', '🐝', 'https://www.britannica.com/animal/honeybee'),
  _rf(
    'rf054',
    '🌈',
    'https://www.scientificamerican.com/article/rainbow-facts/',
  ),
  _rf(
    'rf055',
    '🦎',
    'https://www.nationalgeographic.com/animals/article/axolotl',
  ),
  _rf('rf056', '🧲', 'https://www.nasa.gov/solar-system/earths-magnetosphere/'),
  _rf('rf057', '🦷', 'https://www.britannica.com/animal/shark'),
  _rf(
    'rf058',
    '🗼',
    'https://www.britannica.com/topic/Eiffel-Tower-Paris-France',
  ),
  _rf(
    'rf059',
    '🐧',
    'https://www.nationalgeographic.com/animals/article/emperor-penguin',
  ),
  _rf('rf060', '🧪', 'https://www.britannica.com/biography/Marie-Curie'),
  _rf(
    'rf061',
    '🦅',
    'https://www.nationalgeographic.com/animals/article/bald-eagle',
  ),
  _rf('rf062', '🌪️', 'https://www.britannica.com/science/tornado'),
  _rf('rf063', '🐻', 'https://www.worldwildlife.org/species/polar-bear'),
  _rf('rf064', '🔊', 'https://www.britannica.com/science/sound-physics'),
  _rf(
    'rf065',
    '🐺',
    'https://www.nationalgeographic.com/animals/article/wolf-facts',
  ),
  _rf('rf066', '🏰', 'https://www.britannica.com/topic/Great-Pyramid-of-Giza'),
  _rf('rf067', '🕷️', 'https://www.livescience.com/spider-silk-strength.html'),
  _rf('rf068', '🌺', 'https://www.britannica.com/plant/corpse-flower'),
  _rf(
    'rf069',
    '🦥',
    'https://www.nationalgeographic.com/animals/article/three-toed-sloth',
  ),
  _rf('rf070', '🧂', 'https://www.britannica.com/place/Dead-Sea'),
  _rf(
    'rf071',
    '🐢',
    'https://www.nationalgeographic.com/animals/article/galapagos-tortoise',
  ),
  _rf('rf072', '🌙', 'https://www.nasa.gov/moon/'),
  _rf('rf073', '🦜', 'https://www.britannica.com/animal/parrot'),
  _rf(
    'rf074',
    '🎵',
    'https://www.scientificamerican.com/article/why-does-music-make-us-feel/',
  ),
  _rf(
    'rf075',
    '🐋',
    'https://www.nationalgeographic.com/animals/article/humpback-whale',
  ),
  _rf('rf076', '🧊', 'https://www.britannica.com/place/Antarctica'),
  _rf(
    'rf077',
    '🦔',
    'https://www.nationalgeographic.com/animals/article/hedgehog',
  ),
  _rf('rf078', '🌌', 'https://www.nasa.gov/milky-way-galaxy/'),
  _rf(
    'rf079',
    '🐄',
    'https://www.smithsonianmag.com/smart-news/cows-have-best-friends-180957081/',
  ),
  _rf('rf080', '💎', 'https://www.britannica.com/science/diamond'),
  _rf('rf081', '🦩', 'https://www.livescience.com/27344-flamingos.html'),
  _rf('rf082', '🏔️', 'https://www.britannica.com/place/Mariana-Trench'),
  _rf(
    'rf083',
    '🐸',
    'https://www.nationalgeographic.com/animals/article/poison-dart-frog',
  ),
  _rf('rf084', '📡', 'https://www.nasa.gov/voyager/'),
  _rf('rf085', '🐟', 'https://www.britannica.com/animal/clownfish'),
  _rf(
    'rf086',
    '🌿',
    'https://www.nationalgeographic.com/environment/article/photosynthesis',
  ),
  _rf('rf087', '🦋', 'https://www.britannica.com/animal/monarch-butterfly'),
  _rf(
    'rf088',
    '🗿',
    'https://www.history.com/topics/south-america/easter-island',
  ),
  _rf(
    'rf089',
    '🐊',
    'https://www.nationalgeographic.com/animals/article/saltwater-crocodile',
  ),
  _rf(
    'rf090',
    '💧',
    'https://www.usgs.gov/special-topics/water-science-school/science/water-you-water-and-human-body',
  ),
  _rf('rf091', '🦚', 'https://www.britannica.com/animal/peacock-bird'),
  _rf('rf092', '🌡️', 'https://www.space.com/18175-venus-temperature.html'),
  _rf(
    'rf093',
    '🐉',
    'https://www.nationalgeographic.com/animals/article/komodo-dragon',
  ),
  _rf('rf094', '🧲', 'https://www.britannica.com/place/Bermuda-Triangle'),
  _rf('rf095', '🐃', 'https://www.livescience.com/27503-hippos.html'),
  _rf('rf096', '⏰', 'https://www.britannica.com/science/circadian-rhythm'),
  _rf(
    'rf097',
    '🦠',
    'https://www.scientificamerican.com/article/strange-but-true-humans-glow-in-visible-light/',
  ),
  _rf('rf098', '🗻', 'https://www.britannica.com/place/Mauna-Kea'),
  _rf(
    'rf099',
    '🐌',
    'https://www.nationalgeographic.com/animals/article/garden-snail',
  ),
  _rf(
    'rf100',
    '🧫',
    'https://www.livescience.com/33179-does-stomach-acid-dissolve-metal.html',
  ),
  _rf(
    'rf101',
    '🦂',
    'https://www.nationalgeographic.com/animals/article/scorpion',
  ),
  _rf('rf102', '🌊', 'https://www.britannica.com/science/tsunami'),
  _rf(
    'rf103',
    '🐨',
    'https://www.nationalgeographic.com/animals/article/koala',
  ),
  _rf('rf104', '🔭', 'https://www.nasa.gov/mission/hubble-space-telescope/'),
  _rf('rf105', '🦑', 'https://www.britannica.com/animal/giant-squid'),
  _rf('rf106', '🧲', 'https://www.livescience.com/38059-magnetism.html'),
  _rf(
    'rf107',
    '🐆',
    'https://www.nationalgeographic.com/animals/article/cheetah',
  ),
  _rf('rf108', '🌕', 'https://www.britannica.com/science/tidal-force'),
  _rf('rf109', '🦇', 'https://www.nationalgeographic.com/animals/article/bats'),
  _rf(
    'rf110',
    '⛏️',
    'https://www.britannica.com/science/gold-chemical-element',
  ),
  _rf(
    'rf111',
    '🐕',
    'https://www.smithsonianmag.com/science-nature/dog-domestication-history-180978027/',
  ),
  _rf('rf112', '☄️', 'https://www.nasa.gov/solar-system/asteroids/'),
  _rf(
    'rf113',
    '🦓',
    'https://www.nationalgeographic.com/animals/article/zebra',
  ),
  _rf('rf114', '🧊', 'https://www.britannica.com/place/Greenland'),
  _rf('rf115', '🐠', 'https://www.livescience.com/55468-how-fish-breathe.html'),
  _rf('rf116', '🏜️', 'https://www.britannica.com/place/Atacama-Desert'),
  _rf(
    'rf117',
    '🦊',
    'https://www.nationalgeographic.com/animals/article/arctic-fox',
  ),
  _rf('rf118', '🌑', 'https://www.nasa.gov/solar-system/planets/mercury/'),
  _rf('rf119', '🐪', 'https://www.britannica.com/animal/camel'),
  _rf(
    'rf120',
    '🌿',
    'https://www.nationalgeographic.com/environment/article/amazon-rainforest',
  ),
  _rf('rf121', '🦏', 'https://www.worldwildlife.org/species/rhinoceros'),
  _rf('rf122', '💨', 'https://www.britannica.com/science/atmosphere'),
  _rf(
    'rf123',
    '🐈',
    'https://www.smithsonianmag.com/history/a-brief-history-of-house-cats-158390681/',
  ),
  _rf('rf124', '🌊', 'https://www.nasa.gov/earth/water/'),
  _rf('rf125', '🦉', 'https://www.nationalgeographic.com/animals/article/owl'),
  _rf('rf126', '🧬', 'https://www.livescience.com/37247-dna-human-body.html'),
  _rf('rf127', '🐡', 'https://www.britannica.com/animal/pufferfish'),
  _rf(
    'rf128',
    '🏔️',
    'https://www.nationalgeographic.com/environment/article/mount-kilimanjaro',
  ),
  _rf('rf129', '🦘', 'https://www.britannica.com/animal/kangaroo'),
  _rf('rf130', '🌋', 'https://www.britannica.com/science/volcano'),
  _rf(
    'rf131',
    '🐿️',
    'https://www.nationalgeographic.com/animals/article/squirrel',
  ),
  _rf(
    'rf132',
    '🧪',
    'https://www.britannica.com/science/helium-chemical-element',
  ),
  _rf(
    'rf133',
    '🦩',
    'https://www.livescience.com/55622-why-are-flamingos-pink.html',
  ),
  _rf('rf134', '🌍', 'https://www.britannica.com/place/Pacific-Ocean'),
  _rf(
    'rf135',
    '🐗',
    'https://www.nationalgeographic.com/animals/article/warthog',
  ),
  _rf(
    'rf136',
    '❄️',
    'https://www.britannica.com/science/snowflake-ice-crystal',
  ),
  _rf(
    'rf137',
    '🦃',
    'https://www.smithsonianmag.com/science-nature/14-fun-facts-about-turkeys-180947429/',
  ),
  _rf(
    'rf138',
    '🌊',
    'https://www.nationalgeographic.com/environment/article/great-barrier-reef',
  ),
  _rf('rf139', '🐁', 'https://www.britannica.com/animal/mouse-rodent'),
  _rf(
    'rf140',
    '🏛️',
    'https://www.history.com/topics/ancient-history/ancient-rome',
  ),
  _rf(
    'rf141',
    '🦛',
    'https://www.nationalgeographic.com/animals/article/hippopotamus',
  ),
  _rf('rf142', '☁️', 'https://www.britannica.com/science/cloud-meteorology'),
  _rf('rf143', '🐝', 'https://www.livescience.com/bees-waggle-dance.html'),
  _rf(
    'rf144',
    '🪨',
    'https://www.nationalgeographic.com/science/article/grand-canyon',
  ),
  _rf('rf145', '🦎', 'https://www.britannica.com/animal/chameleon-lizard'),
  _rf(
    'rf146',
    '🌐',
    'https://www.livescience.com/43584-earth-magnetic-field.html',
  ),
  _rf(
    'rf147',
    '🐒',
    'https://www.nationalgeographic.com/animals/article/chimpanzee',
  ),
  _rf(
    'rf148',
    '💎',
    'https://www.britannica.com/science/carbon-chemical-element',
  ),
  _rf(
    'rf149',
    '🦭',
    'https://www.nationalgeographic.com/animals/article/walrus',
  ),
  _rf('rf150', '🌑', 'https://www.nasa.gov/solar-system/planets/neptune/'),
  _rf('rf151', '🐞', 'https://www.britannica.com/animal/ladybug'),
  _rf(
    'rf152',
    '🧊',
    'https://www.nationalgeographic.com/environment/article/ice-age',
  ),
  _rf(
    'rf153',
    '🦪',
    'https://www.livescience.com/32289-how-do-oysters-make-pearls.html',
  ),
  _rf('rf154', '🌍', 'https://www.britannica.com/place/Nile-River'),
  _rf(
    'rf155',
    '🐫',
    'https://www.nationalgeographic.com/animals/article/dromedary-camel',
  ),
  _rf('rf156', '🔥', 'https://www.britannica.com/science/fire'),
  _rf(
    'rf157',
    '🦨',
    'https://www.nationalgeographic.com/animals/article/skunk',
  ),
  _rf(
    'rf158',
    '🌙',
    'https://www.space.com/55-earths-moon-formation-composition-and-orbit.html',
  ),
  _rf('rf159', '🐛', 'https://www.britannica.com/animal/butterfly-insect'),
  _rf(
    'rf160',
    '🗻',
    'https://www.nationalgeographic.com/environment/article/himalayas',
  ),
  _rf('rf161', '🦦', 'https://www.worldwildlife.org/species/sea-otter'),
  _rf('rf162', '🧪', 'https://www.britannica.com/science/oxygen'),
  _rf(
    'rf163',
    '🐍',
    'https://www.nationalgeographic.com/animals/article/king-cobra',
  ),
  _rf('rf164', '🌊', 'https://www.britannica.com/science/ocean-current'),
  _rf(
    'rf165',
    '🦙',
    'https://www.nationalgeographic.com/animals/article/llama',
  ),
  _rf('rf166', '🏔️', 'https://www.livescience.com/tallest-mountains.html'),
  _rf('rf167', '🐳', 'https://www.britannica.com/animal/sperm-whale'),
  _rf(
    'rf168',
    '🌍',
    'https://www.nationalgeographic.com/environment/article/continental-drift',
  ),
  _rf('rf169', '🐿️', 'https://www.livescience.com/squirrels-facts.html'),
  _rf('rf170', '⚗️', 'https://www.britannica.com/science/periodic-table'),
  _rf(
    'rf171',
    '🐝',
    'https://www.nationalgeographic.com/animals/article/bumblebee',
  ),
  _rf('rf172', '🌪️', 'https://www.britannica.com/science/hurricane'),
  _rf(
    'rf173',
    '🦫',
    'https://www.nationalgeographic.com/animals/article/beaver',
  ),
  _rf(
    'rf174',
    '🌡️',
    'https://www.livescience.com/hottest-temperatures-on-earth.html',
  ),
  _rf('rf175', '🐕‍🦺', 'https://www.britannica.com/animal/dog'),
  _rf('rf176', '💫', 'https://www.nasa.gov/solar-system/planets/jupiter/'),
  _rf('rf177', '🦤', 'https://www.britannica.com/animal/dodo-extinct-bird'),
  _rf(
    'rf178',
    '🌿',
    'https://www.nationalgeographic.com/environment/article/deforestation',
  ),
  _rf('rf179', '🐴', 'https://www.livescience.com/horse-facts.html'),
  _rf('rf180', '🌊', 'https://www.britannica.com/place/Mediterranean-Sea'),
  _rf(
    'rf181',
    '🦩',
    'https://www.nationalgeographic.com/animals/article/greater-flamingo',
  ),
  _rf('rf182', '🧲', 'https://www.space.com/15680-solar-flares-facts.html'),
  _rf(
    'rf183',
    '🐻‍❄️',
    'https://www.nationalgeographic.com/animals/article/polar-bear',
  ),
  _rf('rf184', '🌑', 'https://www.britannica.com/science/black-hole'),
  _rf(
    'rf185',
    '🦀',
    'https://www.nationalgeographic.com/animals/article/japanese-spider-crab',
  ),
  _rf('rf186', '🌊', 'https://www.livescience.com/deepest-point-in-ocean.html'),
  _rf('rf187', '🐼', 'https://www.worldwildlife.org/species/giant-panda'),
  _rf('rf188', '⚡', 'https://www.britannica.com/science/electricity'),
  _rf(
    'rf189',
    '🦬',
    'https://www.nationalgeographic.com/animals/article/american-bison',
  ),
  _rf(
    'rf190',
    '🌋',
    'https://www.britannica.com/place/Yellowstone-National-Park',
  ),
  _rf(
    'rf191',
    '🐩',
    'https://www.livescience.com/wolves-dogs-domestication.html',
  ),
  _rf('rf192', '🌙', 'https://www.nasa.gov/solar-system/planets/mars/'),
  _rf(
    'rf193',
    '🦈',
    'https://www.nationalgeographic.com/animals/article/whale-shark',
  ),
  _rf('rf194', '🧬', 'https://www.britannica.com/science/gene'),
  _rf(
    'rf195',
    '🐓',
    'https://www.smithsonianmag.com/science-nature/how-chicken-conquered-world-87583657/',
  ),
  _rf('rf196', '🌍', 'https://www.livescience.com/earth-layers.html'),
  _rf(
    'rf197',
    '🦧',
    'https://www.nationalgeographic.com/animals/article/orangutan',
  ),
  _rf('rf198', '💨', 'https://www.britannica.com/science/wind'),
  _rf(
    'rf199',
    '🐳',
    'https://www.nationalgeographic.com/animals/article/narwhal',
  ),
  _rf('rf200', '🌌', 'https://www.space.com/25100-galaxy-definition.html'),
  _rf('rf201', '🐝', 'https://www.livescience.com/bees-math.html'),
  _rf('rf202', '🌊', 'https://www.britannica.com/science/coral-reef'),
  _rf(
    'rf203',
    '🦕',
    'https://www.nationalgeographic.com/science/article/dinosaurs',
  ),
  _rf('rf204', '🧪', 'https://www.britannica.com/science/water'),
  _rf('rf205', '🐧', 'https://www.livescience.com/penguins-facts.html'),

  // ── Dumb Ways to Die (150+) ───────────────────────────────────────────────
  _dw(
    'dw001',
    '⚖️',
    'https://www.britannica.com/biography/Clement-Vallandigham',
  ),
  _dw(
    'dw002',
    '🍬',
    'https://www.britannica.com/story/did-an-avalanche-of-molasses-really-engulf-boston',
  ),
  _dw(
    'dw003',
    '🚀',
    'https://www.smithsonianmag.com/history/the-engineer-who-rode-the-rocket-sled-89391691/',
  ),
  _dw('dw004', '🍺', 'https://en.wikipedia.org/wiki/London_Beer_Flood'),
  _dw('dw005', '💃', 'https://en.wikipedia.org/wiki/Dancing_plague_of_1518'),
  _dw(
    'dw006',
    '🪟',
    'https://www.atlasobscura.com/articles/the-window-that-killed',
  ),
  _dw('dw007', '🎢', 'https://en.wikipedia.org/wiki/Takakanonuma_Greenland'),
  _dw('dw008', '🏢', 'https://en.wikipedia.org/wiki/Garry_Hoy'),
  _dw(
    'dw009',
    '🛴',
    'https://en.wikipedia.org/wiki/Segway#Death_of_Jimi_Heselden',
  ),
  _dw('dw010', '🪂', 'https://en.wikipedia.org/wiki/Franz_Reichelt'),
  _dw('dw011', '📜', 'https://en.wikipedia.org/wiki/Draco_(lawgiver)'),
  _dw('dw012', '😂', 'https://en.wikipedia.org/wiki/Chrysippus'),
  _dw('dw013', '💀', 'https://en.wikipedia.org/wiki/Sigurd_the_Mighty'),
  _dw('dw014', '🧔', 'https://en.wikipedia.org/wiki/Hans_Steininger'),
  _dw('dw015', '🔭', 'https://en.wikipedia.org/wiki/Tycho_Brahe'),
  _dw('dw016', '😷', 'https://en.wikipedia.org/wiki/Horace_Wells'),
  _dw(
    'dw017',
    '🖨️',
    'https://en.wikipedia.org/wiki/William_Bullock_(inventor)',
  ),
  _dw('dw018', '🧣', 'https://en.wikipedia.org/wiki/Isadora_Duncan'),
  _dw('dw019', '🐔', 'https://en.wikipedia.org/wiki/Basilisk_(lizard)'),
  _dw(
    'dw020',
    '🦷',
    'https://en.wikipedia.org/wiki/Death_of_Sherwood_Anderson',
  ),
  _dw('dw021', '🍊', 'https://en.wikipedia.org/wiki/Bobby_Leach'),
  _dw('dw022', '🥃', 'https://en.wikipedia.org/wiki/Jack_Daniel'),
  _dw('dw023', '🌊', 'https://en.wikipedia.org/wiki/Henry_Winstanley'),
  _dw('dw024', '🚗', 'https://en.wikipedia.org/wiki/Max_Valier'),
  _dw(
    'dw025',
    '🎪',
    'https://en.wikipedia.org/wiki/Philip_of_France_(1116%E2%80%931131)',
  ),
  _dw('dw026', '📖', 'https://en.wikipedia.org/wiki/Aeschylus'),
  _dw('dw027', '🏇', 'https://en.wikipedia.org/wiki/William_the_Conqueror'),
  _dw('dw028', '🍖', 'https://en.wikipedia.org/wiki/Adolf_Frederick'),
  _dw('dw029', '🧪', 'https://en.wikipedia.org/wiki/Thomas_Midgley_Jr.'),
  _dw('dw030', '🎩', 'https://en.wikipedia.org/wiki/William_Henry_Harrison'),
  _dw('dw031', '🪒', 'https://en.wikipedia.org/wiki/Allan_Pinkerton'),
  _dw('dw032', '🎻', 'https://en.wikipedia.org/wiki/Jean-Baptiste_Lully'),
  _dw('dw033', '🍾', 'https://en.wikipedia.org/wiki/Alexander_I_of_Greece'),
  _dw('dw034', '🐍', 'https://en.wikipedia.org/wiki/Cleopatra'),
  _dw('dw035', '🧨', 'https://en.wikipedia.org/wiki/Karel_Soucek'),
  _dw('dw036', '🎬', 'https://en.wikipedia.org/wiki/Brandon_Lee'),
  _dw('dw037', '🏖️', 'https://en.wikipedia.org/wiki/Houdini'),
  _dw('dw038', '🐻', 'https://en.wikipedia.org/wiki/Timothy_Treadwell'),
  _dw('dw039', '🎈', 'https://en.wikipedia.org/wiki/Larry_Walters'),
  _dw(
    'dw040',
    '🛸',
    'https://en.wikipedia.org/wiki/Heaven%27s_Gate_(religious_group)',
  ),
  _dw('dw041', '🧲', 'https://en.wikipedia.org/wiki/Michael_Faraday'),
  _dw('dw042', '🏋️', 'https://en.wikipedia.org/wiki/Milo_of_Croton'),
  _dw('dw043', '🍄', 'https://en.wikipedia.org/wiki/Emperor_Claudius'),
  _dw('dw044', '⚔️', 'https://en.wikipedia.org/wiki/Edward_II_of_England'),
  _dw('dw045', '🐎', 'https://en.wikipedia.org/wiki/Attila'),
  _dw('dw046', '🎭', 'https://en.wikipedia.org/wiki/Mol%C3%A8re'),
  _dw('dw047', '🔔', 'https://en.wikipedia.org/wiki/Alexander_Graham_Bell'),
  _dw('dw048', '🐂', 'https://en.wikipedia.org/wiki/Running_of_the_bulls'),
  _dw('dw049', '🧗', 'https://en.wikipedia.org/wiki/George_Mallory'),
  _dw('dw050', '🏺', 'https://en.wikipedia.org/wiki/Qin_Shi_Huang'),
  _dw('dw051', '🪜', 'https://en.wikipedia.org/wiki/Li_Bai'),
  _dw('dw052', '🐴', 'https://en.wikipedia.org/wiki/Genghis_Khan'),
  _dw('dw053', '🧨', 'https://en.wikipedia.org/wiki/Wan_Hu'),
  _dw('dw054', '🪶', 'https://en.wikipedia.org/wiki/Henry_I_of_England'),
  _dw('dw055', '🐒', 'https://en.wikipedia.org/wiki/Charla_Nash'),
  _dw('dw056', '🎯', 'https://en.wikipedia.org/wiki/William_Tell'),
  _dw('dw057', '🧊', 'https://en.wikipedia.org/wiki/RMS_Titanic'),
  _dw('dw058', '🏰', 'https://en.wikipedia.org/wiki/Countess_Bathory'),
  _dw('dw059', '🪦', 'https://en.wikipedia.org/wiki/Rasputin'),
  _dw('dw060', '🎲', 'https://en.wikipedia.org/wiki/Caligula'),
  _dw('dw061', '🐦', 'https://en.wikipedia.org/wiki/Emu_War'),
  _dw(
    'dw062',
    '🏗️',
    'https://en.wikipedia.org/wiki/Tacoma_Narrows_Bridge_(1940)',
  ),
  _dw('dw063', '🎸', 'https://en.wikipedia.org/wiki/Keith_Relf'),
  _dw('dw064', '🪂', 'https://en.wikipedia.org/wiki/Vesna_Vulovi%C4%87'),
  _dw('dw065', '🐊', 'https://en.wikipedia.org/wiki/Gustave_(crocodile)'),
  _dw('dw066', '🧪', 'https://en.wikipedia.org/wiki/Marie_Curie'),
  _dw('dw067', '🌋', 'https://en.wikipedia.org/wiki/Pliny_the_Elder'),
  _dw('dw068', '⚡', 'https://en.wikipedia.org/wiki/Georg_Wilhelm_Richmann'),
  _dw('dw069', '🎪', 'https://en.wikipedia.org/wiki/Jumbo'),
  _dw('dw070', '🏜️', 'https://en.wikipedia.org/wiki/Death_Valley'),
  _dw('dw071', '🐘', 'https://en.wikipedia.org/wiki/Topsy_(elephant)'),
  _dw('dw072', '🧨', 'https://en.wikipedia.org/wiki/Halifax_Explosion'),
  _dw('dw073', '🐉', 'https://en.wikipedia.org/wiki/Komodo_dragon'),
  _dw('dw074', '🎆', 'https://en.wikipedia.org/wiki/Fireworks#Safety'),
  _dw('dw075', '🐻', 'https://en.wikipedia.org/wiki/Grizzly_Man'),
  _dw('dw076', '⚓', 'https://en.wikipedia.org/wiki/Vasa_(ship)'),
  _dw('dw077', '🏔️', 'https://en.wikipedia.org/wiki/Donner_Party'),
  _dw('dw078', '🐀', 'https://en.wikipedia.org/wiki/Rat_king'),
  _dw('dw079', '💀', 'https://en.wikipedia.org/wiki/Radium_Girls'),
  _dw('dw080', '🌊', 'https://en.wikipedia.org/wiki/Tsunami'),
  _dw('dw081', '🦈', 'https://en.wikipedia.org/wiki/USS_Indianapolis_(CA-35)'),
  _dw('dw082', '⛰️', 'https://en.wikipedia.org/wiki/Dyatlov_Pass_incident'),
  _dw('dw083', '🧲', 'https://en.wikipedia.org/wiki/Ball_lightning'),
  _dw('dw084', '🦠', 'https://en.wikipedia.org/wiki/Typhoid_Mary'),
  _dw('dw085', '🏗️', 'https://en.wikipedia.org/wiki/Leaning_Tower_of_Pisa'),
  _dw('dw086', '🎨', 'https://en.wikipedia.org/wiki/Vincent_van_Gogh'),
  _dw('dw087', '🐝', 'https://en.wikipedia.org/wiki/Africanized_bee'),
  _dw('dw088', '🧊', 'https://en.wikipedia.org/wiki/Shackleton'),
  _dw('dw089', '🐕', 'https://en.wikipedia.org/wiki/Laika'),
  _dw(
    'dw090',
    '🎯',
    'https://en.wikipedia.org/wiki/Assassination_of_Archduke_Franz_Ferdinand',
  ),
  _dw('dw091', '🧨', 'https://en.wikipedia.org/wiki/Tunguska_event'),
  _dw('dw092', '🐃', 'https://en.wikipedia.org/wiki/Stampede'),
  _dw('dw093', '🌊', 'https://en.wikipedia.org/wiki/Johnstown_Flood'),
  _dw('dw094', '⚡', 'https://en.wikipedia.org/wiki/Roy_Sullivan'),
  _dw('dw095', '🎩', 'https://en.wikipedia.org/wiki/Mad_hatter_disease'),
  _dw('dw096', '🐍', 'https://en.wikipedia.org/wiki/Black_mamba'),
  _dw('dw097', '💣', 'https://en.wikipedia.org/wiki/Peshtigo_fire'),
  _dw('dw098', '🐂', 'https://en.wikipedia.org/wiki/Minotaur'),
  _dw('dw099', '🧪', 'https://en.wikipedia.org/wiki/Alexander_Litvinenko'),
  _dw('dw100', '🏰', 'https://en.wikipedia.org/wiki/Tower_of_London'),
  _dw('dw101', '🐊', 'https://en.wikipedia.org/wiki/Battle_of_Ramree_Island'),
  _dw('dw102', '🧨', 'https://en.wikipedia.org/wiki/Texas_City_disaster'),
  _dw('dw103', '🌪️', 'https://en.wikipedia.org/wiki/Tri-State_Tornado'),
  _dw('dw104', '⚔️', 'https://en.wikipedia.org/wiki/Battle_of_Karansebes'),
  _dw('dw105', '🐀', 'https://en.wikipedia.org/wiki/Black_Death'),
  _dw(
    'dw106',
    '🏗️',
    'https://en.wikipedia.org/wiki/Hyatt_Regency_walkway_collapse',
  ),
  _dw('dw107', '🌋', 'https://en.wikipedia.org/wiki/Pompeii'),
  _dw('dw108', '⚓', 'https://en.wikipedia.org/wiki/Mary_Celeste'),
  _dw('dw109', '🐍', 'https://en.wikipedia.org/wiki/Snake_Island_(Brazil)'),
  _dw('dw110', '🧫', 'https://en.wikipedia.org/wiki/Unit_731'),
  _dw('dw111', '🐦', 'https://en.wikipedia.org/wiki/Passenger_pigeon'),
  _dw(
    'dw112',
    '🌊',
    'https://en.wikipedia.org/wiki/Galveston_hurricane_of_1900',
  ),
  _dw('dw113', '🎈', 'https://en.wikipedia.org/wiki/Hindenburg_disaster'),
  _dw('dw114', '🏔️', 'https://en.wikipedia.org/wiki/1970_Ancash_earthquake'),
  _dw('dw115', '🦠', 'https://en.wikipedia.org/wiki/Spanish_flu'),
  _dw('dw116', '⛏️', 'https://en.wikipedia.org/wiki/Centralia_mine_fire'),
  _dw('dw117', '🚂', 'https://en.wikipedia.org/wiki/Great_Train_Wreck_of_1856'),
  _dw('dw118', '🪜', 'https://en.wikipedia.org/wiki/Tower_of_Babel'),
  _dw('dw119', '🐘', 'https://en.wikipedia.org/wiki/War_elephant'),
  _dw('dw120', '⚡', 'https://en.wikipedia.org/wiki/Wardenclyffe_Tower'),
  _dw('dw121', '🧊', 'https://en.wikipedia.org/wiki/Endurance_(ship)'),
  _dw('dw122', '🎲', 'https://en.wikipedia.org/wiki/Russian_roulette'),
  _dw('dw123', '🏰', 'https://en.wikipedia.org/wiki/Masada'),
  _dw('dw124', '🐻', 'https://en.wikipedia.org/wiki/Wojtek_(bear)'),
  _dw('dw125', '🧲', 'https://en.wikipedia.org/wiki/Philadelphia_Experiment'),
  _dw('dw126', '🌊', 'https://en.wikipedia.org/wiki/SS_Eastland'),
  _dw(
    'dw127',
    '🎭',
    'https://en.wikipedia.org/wiki/Assassination_of_Abraham_Lincoln',
  ),
  _dw('dw128', '🏜️', 'https://en.wikipedia.org/wiki/Lost_Colony_of_Roanoke'),
  _dw('dw129', '🐍', 'https://en.wikipedia.org/wiki/Pit_viper'),
  _dw('dw130', '🧨', 'https://en.wikipedia.org/wiki/Gunpowder_Plot'),
  _dw('dw131', '🦴', 'https://en.wikipedia.org/wiki/Catacombs_of_Paris'),
  _dw('dw132', '🌋', 'https://en.wikipedia.org/wiki/Mount_Vesuvius'),
  _dw('dw133', '⛏️', 'https://en.wikipedia.org/wiki/Coober_Pedy'),
  _dw('dw134', '🐊', 'https://en.wikipedia.org/wiki/Sobek'),
  _dw('dw135', '🧪', 'https://en.wikipedia.org/wiki/Greek_fire'),
  _dw('dw136', '🏗️', 'https://en.wikipedia.org/wiki/Colossus_of_Rhodes'),
  _dw('dw137', '🧲', 'https://en.wikipedia.org/wiki/Bermuda_Triangle'),
  _dw('dw138', '🐃', 'https://en.wikipedia.org/wiki/Great_Famine_(Ireland)'),
  _dw('dw139', '💀', 'https://en.wikipedia.org/wiki/Sedlec_Ossuary'),
  _dw('dw140', '🌊', 'https://en.wikipedia.org/wiki/Maelstrom'),
  _dw('dw141', '🐦', 'https://en.wikipedia.org/wiki/Great_Auk'),
  _dw(
    'dw142',
    '🧊',
    'https://en.wikipedia.org/wiki/Franklin%27s_lost_expedition',
  ),
  _dw('dw143', '⚡', 'https://en.wikipedia.org/wiki/Tunguska_event'),
  _dw('dw144', '🏴‍☠️', 'https://en.wikipedia.org/wiki/Blackbeard'),
  _dw('dw145', '🐀', 'https://en.wikipedia.org/wiki/Plague_of_Justinian'),
  _dw('dw146', '🌋', 'https://en.wikipedia.org/wiki/Krakatoa'),
  _dw('dw147', '📜', 'https://en.wikipedia.org/wiki/Library_of_Alexandria'),
  _dw('dw148', '⚔️', 'https://en.wikipedia.org/wiki/Battle_of_Thermopylae'),
  _dw('dw149', '🧨', 'https://en.wikipedia.org/wiki/Chernobyl_disaster'),
  _dw(
    'dw150',
    '🏗️',
    'https://en.wikipedia.org/wiki/Hanging_Gardens_of_Babylon',
  ),
  _dw('dw151', '🐘', 'https://en.wikipedia.org/wiki/Hannibal'),
  _dw('dw152', '💀', 'https://en.wikipedia.org/wiki/Danse_Macabre'),
  _dw('dw153', '🌊', 'https://en.wikipedia.org/wiki/Bermeja'),
  _dw('dw154', '🐍', 'https://en.wikipedia.org/wiki/Ouroboros'),
  _dw('dw155', '🧪', 'https://en.wikipedia.org/wiki/Bhopal_disaster'),
];
