import 'sipdeck_models.dart';
import '../../../../core/i18n/app_localizations.dart';

List<SipDeckCard> generateSipDeckExpansion(AppLocalizations l10n) {
  return [
  SipDeckCard(
    id: 'w100',
    emoji: '🧠',
    text: l10n.get('sd_card_w100'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w101',
    emoji: '🎤',
    text: l10n.get('sd_card_w101'),
    sips: 3,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w102',
    emoji: '👕',
    text: l10n.get('sd_card_w102'),
    sips: 1,
    category: SipDeckCategory.warmUp,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'w103',
    emoji: '🤚',
    text: l10n.get('sd_card_w103'),
    sips: 1,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w104',
    emoji: '🚗',
    text: l10n.get('sd_card_w104'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'w105',
    emoji: '🍕',
    text: l10n.get('sd_card_w105'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w106',
    emoji: '🐶',
    text: l10n.get('sd_card_w106'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'w107',
    emoji: '🥶',
    text: l10n.get('sd_card_w107'),
    sips: 1,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w108',
    emoji: '📱',
    text: l10n.get('sd_card_w108'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w109',
    emoji: '👟',
    text: l10n.get('sd_card_w109'),
    sips: 1,
    category: SipDeckCategory.warmUp,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'w110',
    emoji: '🌍',
    text: l10n.get('sd_card_w110'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'w111',
    emoji: '🎧',
    text: l10n.get('sd_card_w111'),
    sips: 1,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w112',
    emoji: '☕',
    text: l10n.get('sd_card_w112'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w113',
    emoji: '📺',
    text: l10n.get('sd_card_w113'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w114',
    emoji: '👶',
    text: l10n.get('sd_card_w114'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'w115',
    emoji: '👴',
    text: l10n.get('sd_card_w115'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'w116',
    emoji: '📅',
    text: l10n.get('sd_card_w116'),
    sips: 1,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w117',
    emoji: '🦘',
    text: l10n.get('sd_card_w117'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w118',
    emoji: '🎸',
    text: l10n.get('sd_card_w118'),
    sips: 3,
    category: SipDeckCategory.warmUp,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'w119',
    emoji: '👏',
    text: l10n.get('sd_card_w119'),
    sips: 2,
    category: SipDeckCategory.warmUp,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc100',
    emoji: '🔀',
    text: l10n.get('sd_card_wc100'),
    sips: 0,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc101',
    emoji: '👻',
    text: l10n.get('sd_card_wc101'),
    sips: 2,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc102',
    emoji: '👑',
    text: l10n.get('sd_card_wc102'),
    sips: 1,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc103',
    emoji: '🤐',
    text: l10n.get('sd_card_wc103'),
    sips: 2,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc104',
    emoji: '🤖',
    text: l10n.get('sd_card_wc104'),
    sips: 3,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc105',
    emoji: '🥸',
    text: l10n.get('sd_card_wc105'),
    sips: 1,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc106',
    emoji: '🦄',
    text: l10n.get('sd_card_wc106'),
    sips: 2,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc107',
    emoji: '📸',
    text: l10n.get('sd_card_wc107'),
    sips: 5,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc108',
    emoji: '👽',
    text: l10n.get('sd_card_wc108'),
    sips: 3,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc109',
    emoji: '📞',
    text: l10n.get('sd_card_wc109'),
    sips: 4,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc110',
    emoji: '🦖',
    text: l10n.get('sd_card_wc110'),
    sips: 3,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc111',
    emoji: '🪙',
    text: l10n.get('sd_card_wc111'),
    sips: 2,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc112',
    emoji: '🌪️',
    text: l10n.get('sd_card_wc112'),
    sips: 2,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc113',
    emoji: '🧊',
    text: l10n.get('sd_card_wc113'),
    sips: 4,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc114',
    emoji: '🪡',
    text: l10n.get('sd_card_wc114'),
    sips: 3,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc115',
    emoji: '🎭',
    text: l10n.get('sd_card_wc115'),
    sips: 2,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc116',
    emoji: '🔒',
    text: l10n.get('sd_card_wc116'),
    sips: 1,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'wc117',
    emoji: '🪖',
    text: l10n.get('sd_card_wc117'),
    sips: 2,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc118',
    emoji: '🤫',
    text: l10n.get('sd_card_wc118'),
    sips: 0,
    category: SipDeckCategory.wildCards,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'wc119',
    emoji: '✨',
    text: l10n.get('sd_card_wc119'),
    sips: 0,
    category: SipDeckCategory.wildCards,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f100',
    emoji: '🔥',
    text: l10n.get('sd_card_f100'),
    sips: 4,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f101',
    emoji: '👀',
    text: l10n.get('sd_card_f101'),
    sips: 3,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f102',
    emoji: '💋',
    text: l10n.get('sd_card_f102'),
    sips: 3,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f103',
    emoji: '😏',
    text: l10n.get('sd_card_f103'),
    sips: 4,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f104',
    emoji: '🌹',
    text: l10n.get('sd_card_f104'),
    sips: 3,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f105',
    emoji: '💕',
    text: l10n.get('sd_card_f105'),
    sips: 4,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f106',
    emoji: '🍑',
    text: l10n.get('sd_card_f106'),
    sips: 5,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f107',
    emoji: '😘',
    text: l10n.get('sd_card_f107'),
    sips: 2,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f108',
    emoji: '🌶️',
    text: l10n.get('sd_card_f108'),
    sips: 1,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f109',
    emoji: '💌',
    text: l10n.get('sd_card_f109'),
    sips: 5,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f110',
    emoji: '😈',
    text: l10n.get('sd_card_f110'),
    sips: 2,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f111',
    emoji: '👄',
    text: l10n.get('sd_card_f111'),
    sips: 3,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f112',
    emoji: '🍓',
    text: l10n.get('sd_card_f112'),
    sips: 4,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f113',
    emoji: '💞',
    text: l10n.get('sd_card_f113'),
    sips: 0,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f114',
    emoji: '📱',
    text: l10n.get('sd_card_f114'),
    sips: 5,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f115',
    emoji: '🤫',
    text: l10n.get('sd_card_f115'),
    sips: 0,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f116',
    emoji: '🖤',
    text: l10n.get('sd_card_f116'),
    sips: 2,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f117',
    emoji: '💃',
    text: l10n.get('sd_card_f117'),
    sips: 4,
    category: SipDeckCategory.flirty,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'f118',
    emoji: '🤤',
    text: l10n.get('sd_card_f118'),
    sips: 3,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'f119',
    emoji: '💘',
    text: l10n.get('sd_card_f119'),
    sips: 2,
    category: SipDeckCategory.flirty,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b100',
    emoji: '🥂',
    text: l10n.get('sd_card_b100'),
    sips: 0,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b101',
    emoji: '🚽',
    text: l10n.get('sd_card_b101'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'b102',
    emoji: '🎶',
    text: l10n.get('sd_card_b102'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b103',
    emoji: '🧊',
    text: l10n.get('sd_card_b103'),
    sips: 1,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b104',
    emoji: '🍹',
    text: l10n.get('sd_card_b104'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b105',
    emoji: '🍺',
    text: l10n.get('sd_card_b105'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'b106',
    emoji: '💸',
    text: l10n.get('sd_card_b106'),
    sips: 3,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'b107',
    emoji: '🗣️',
    text: l10n.get('sd_card_b107'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b108',
    emoji: '🧢',
    text: l10n.get('sd_card_b108'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'b109',
    emoji: '🧥',
    text: l10n.get('sd_card_b109'),
    sips: 1,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b110',
    emoji: '🚕',
    text: l10n.get('sd_card_b110'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b111',
    emoji: '🍟',
    text: l10n.get('sd_card_b111'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'b112',
    emoji: '⏱️',
    text: l10n.get('sd_card_b112'),
    sips: 3,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b113',
    emoji: '💧',
    text: l10n.get('sd_card_b113'),
    sips: 0,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b114',
    emoji: '🤝',
    text: l10n.get('sd_card_b114'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 4,
  ),
  SipDeckCard(
    id: 'b115',
    emoji: '📸',
    text: l10n.get('sd_card_b115'),
    sips: 1,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'b116',
    emoji: '🎉',
    text: l10n.get('sd_card_b116'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'b117',
    emoji: '💳',
    text: l10n.get('sd_card_b117'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'b118',
    emoji: '🍷',
    text: l10n.get('sd_card_b118'),
    sips: 0,
    category: SipDeckCategory.barNight,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'b119',
    emoji: '🎲',
    text: l10n.get('sd_card_b119'),
    sips: 2,
    category: SipDeckCategory.barNight,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'l100',
    emoji: '🤪',
    text: l10n.get('sd_card_l100'),
    sips: 2,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l101',
    emoji: '👽',
    text: l10n.get('sd_card_l101'),
    sips: 3,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l102',
    emoji: '🐒',
    text: l10n.get('sd_card_l102'),
    sips: 4,
    category: SipDeckCategory.laughs,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'l103',
    emoji: '👃',
    text: l10n.get('sd_card_l103'),
    sips: 2,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l104',
    emoji: '🐄',
    text: l10n.get('sd_card_l104'),
    sips: 1,
    category: SipDeckCategory.laughs,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'l105',
    emoji: '🛒',
    text: l10n.get('sd_card_l105'),
    sips: 2,
    category: SipDeckCategory.laughs,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'l106',
    emoji: '🍕',
    text: l10n.get('sd_card_l106'),
    sips: 3,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l107',
    emoji: '🧙',
    text: l10n.get('sd_card_l107'),
    sips: 1,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l108',
    emoji: '🕵️',
    text: l10n.get('sd_card_l108'),
    sips: 2,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l109',
    emoji: '🤯',
    text: l10n.get('sd_card_l109'),
    sips: 2,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l110',
    emoji: '🧸',
    text: l10n.get('sd_card_l110'),
    sips: 0,
    category: SipDeckCategory.laughs,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'l111',
    emoji: '🗣️',
    text: l10n.get('sd_card_l111'),
    sips: 0,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l112',
    emoji: '👶',
    text: l10n.get('sd_card_l112'),
    sips: 4,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l113',
    emoji: '🦅',
    text: l10n.get('sd_card_l113'),
    sips: 0,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l114',
    emoji: '🚗',
    text: l10n.get('sd_card_l114'),
    sips: 0,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l115',
    emoji: '🤖',
    text: l10n.get('sd_card_l115'),
    sips: 2,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  SipDeckCard(
    id: 'l116',
    emoji: '🎤',
    text: l10n.get('sd_card_l116'),
    sips: 0,
    category: SipDeckCategory.laughs,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'l117',
    emoji: '🪑',
    text: l10n.get('sd_card_l117'),
    sips: 3,
    category: SipDeckCategory.laughs,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'l118',
    emoji: '😭',
    text: l10n.get('sd_card_l118'),
    sips: 3,
    category: SipDeckCategory.laughs,
    minPlayers: 3,
  ),
  SipDeckCard(
    id: 'l119',
    emoji: '🦸',
    text: l10n.get('sd_card_l119'),
    sips: 2,
    category: SipDeckCategory.laughs,
    minPlayers: 2,
  ),
  ];
}
