import 'sudoku_models.dart';

class SudokuCampaignLevel {
  final int levelId;
  final String title;
  final String description;
  final SudokuVariant variant;
  final SudokuDifficulty difficulty;
  final int targetTimeSeconds;
  final String seed;

  const SudokuCampaignLevel({
    required this.levelId,
    required this.title,
    required this.description,
    required this.variant,
    required this.difficulty,
    required this.targetTimeSeconds,
    required this.seed,
  });
}

const List<SudokuCampaignLevel> sudokuCampaignLevels = [
  SudokuCampaignLevel(
    levelId: 1,
    title: 'First Steps',
    description: 'A quick 6x6 board to warm up your brain cells.',
    variant: SudokuVariant.mini6x6,
    difficulty: SudokuDifficulty.easy,
    targetTimeSeconds: 180,
    seed: 'academy_level_1_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 2,
    title: 'Standard Basics',
    description: 'Introduction to standard 9x9 Sudoku.',
    variant: SudokuVariant.standard,
    difficulty: SudokuDifficulty.easy,
    targetTimeSeconds: 420,
    seed: 'academy_level_2_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 3,
    title: 'X Factor',
    description: 'Try out the Diagonal rules on this easy grid.',
    variant: SudokuVariant.diagonal,
    difficulty: SudokuDifficulty.easy,
    targetTimeSeconds: 480,
    seed: 'academy_level_3_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 4,
    title: 'Windoku Windup',
    description: 'Get familiar with four shaded hyper regions.',
    variant: SudokuVariant.hyper,
    difficulty: SudokuDifficulty.easy,
    targetTimeSeconds: 540,
    seed: 'academy_level_4_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 5,
    title: 'Speedy Six',
    description: 'Complete this 6x6 board in under 2 minutes!',
    variant: SudokuVariant.mini6x6,
    difficulty: SudokuDifficulty.medium,
    targetTimeSeconds: 120,
    seed: 'academy_level_5_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 6,
    title: 'Medium Standard',
    description: 'Standard rules with slightly fewer clues.',
    variant: SudokuVariant.standard,
    difficulty: SudokuDifficulty.medium,
    targetTimeSeconds: 480,
    seed: 'academy_level_6_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 7,
    title: 'Double Diagonal',
    description: 'Sudoku X with a medium difficulty layout.',
    variant: SudokuVariant.diagonal,
    difficulty: SudokuDifficulty.medium,
    targetTimeSeconds: 600,
    seed: 'academy_level_7_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 8,
    title: 'Hyper Challenge',
    description: 'Windoku grids with medium difficulty clues.',
    variant: SudokuVariant.hyper,
    difficulty: SudokuDifficulty.medium,
    targetTimeSeconds: 660,
    seed: 'academy_level_8_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 9,
    title: 'Rapid Solver',
    description: 'Solve this easy standard board under pressure.',
    variant: SudokuVariant.standard,
    difficulty: SudokuDifficulty.easy,
    targetTimeSeconds: 240,
    seed: 'academy_level_9_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 10,
    title: 'Six Expert',
    description: 'An expert 6x6 board requiring advanced logic.',
    variant: SudokuVariant.mini6x6,
    difficulty: SudokuDifficulty.expert,
    targetTimeSeconds: 180,
    seed: 'academy_level_10_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 11,
    title: 'Standard Hard',
    description: 'Solve a challenging standard 9x9 grid.',
    variant: SudokuVariant.standard,
    difficulty: SudokuDifficulty.hard,
    targetTimeSeconds: 720,
    seed: 'academy_level_11_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 12,
    title: 'Diagonal Heat',
    description: 'Diagonal X rules on a hard board.',
    variant: SudokuVariant.diagonal,
    difficulty: SudokuDifficulty.hard,
    targetTimeSeconds: 780,
    seed: 'academy_level_12_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 13,
    title: 'Hyper Heavy',
    description: 'Windoku hyper rules on a hard board.',
    variant: SudokuVariant.hyper,
    difficulty: SudokuDifficulty.hard,
    targetTimeSeconds: 840,
    seed: 'academy_level_13_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 14,
    title: 'Sprint Master',
    description: 'Solve a medium standard grid in under 5 minutes.',
    variant: SudokuVariant.standard,
    difficulty: SudokuDifficulty.medium,
    targetTimeSeconds: 300,
    seed: 'academy_level_14_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 15,
    title: 'Standard Expert',
    description: 'The ultimate standard grid challenge.',
    variant: SudokuVariant.standard,
    difficulty: SudokuDifficulty.expert,
    targetTimeSeconds: 900,
    seed: 'academy_level_15_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 16,
    title: 'Expert X',
    description: 'An expert-level Sudoku X board.',
    variant: SudokuVariant.diagonal,
    difficulty: SudokuDifficulty.expert,
    targetTimeSeconds: 1020,
    seed: 'academy_level_16_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 17,
    title: 'Hyper Expert',
    description: 'Hyper Sudoku rules on an expert board.',
    variant: SudokuVariant.hyper,
    difficulty: SudokuDifficulty.expert,
    targetTimeSeconds: 1080,
    seed: 'academy_level_17_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 18,
    title: 'Double Trouble',
    description: 'Solve this expert diagonal grid under 12 minutes.',
    variant: SudokuVariant.diagonal,
    difficulty: SudokuDifficulty.expert,
    targetTimeSeconds: 720,
    seed: 'academy_level_18_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 19,
    title: 'The Storm',
    description: 'An expert hyper grid under 12 minutes.',
    variant: SudokuVariant.hyper,
    difficulty: SudokuDifficulty.expert,
    targetTimeSeconds: 720,
    seed: 'academy_level_19_seed_val',
  ),
  SudokuCampaignLevel(
    levelId: 20,
    title: 'Sudoku Grandmaster',
    description: 'The final, ultimate test of logic and speed.',
    variant: SudokuVariant.standard,
    difficulty: SudokuDifficulty.expert,
    targetTimeSeconds: 600,
    seed: 'academy_level_20_seed_val',
  ),
];
