name: NEX CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/validation.yml

  build-android-web:
    needs: validate
    name: Build Android & Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build Web
        run: |
          flutter build web --release --base-href "/"
        working-directory: nexscore

      - name: Build Android APK
        run: flutter build apk --release
        working-directory: nexscore

      - name: Build Docker Image for Web
        run: |
          docker build -t nexscore-web:latest -f Dockerfile .
        working-directory: nexscore

  build-ios:
    needs: validate
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build iOS IPA (Unsigned)
        run: flutter build ios --release --no-codesign
        working-directory: nexscore
